fix(deps): update dependency org.springframework.boot:spring-boot-starter-parent to v2.7.18 (#1314)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.springframework.boot:spring-boot-starter-parent](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | `2.7.15` -> `2.7.18` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework.boot:spring-boot-starter-parent/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework.boot:spring-boot-starter-parent/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework.boot:spring-boot-starter-parent/2.7.15/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework.boot:spring-boot-starter-parent/2.7.15/2.7.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>spring-projects/spring-boot (org.springframework.boot:spring-boot-starter-parent)</summary>

### [`v2.7.18`](https://togithub.com/spring-projects/spring-boot/releases/tag/v2.7.18)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.7.17...v2.7.18)

#### ⚠️ Noteworthy Changes

-   Following the Paketo team's [announcement](https://blog.paketo.io/posts/paketo-bionic-builder-is-unsafe/) that the Bionic CNB builders will be removed, the default builder using by `bootBuildImage` (Gradle) and `spring-boot:build-image` (Maven) has been changed to Paketo Jammy [#&#8203;38477](https://togithub.com/spring-projects/spring-boot/issues/38477)

#### :lady_beetle: Bug Fixes

-   App fails to start with a NoSuchMethodError when using Flyway 10.0.0 [#&#8203;38164](https://togithub.com/spring-projects/spring-boot/issues/38164)
-   spring.webflux.multipart.max-disk-usage-per-part behaves incorrectly for values where the number of bytes overflows an int [#&#8203;38146](https://togithub.com/spring-projects/spring-boot/issues/38146)
-   Mail health indicator fails when host is not set in properties [#&#8203;38007](https://togithub.com/spring-projects/spring-boot/issues/38007)

#### :notebook_with_decorative_cover: Documentation

-   Document supported SQL comment prefixes [#&#8203;38385](https://togithub.com/spring-projects/spring-boot/pull/38385)
-   Fix link to Elasticsearch health indicator [#&#8203;38330](https://togithub.com/spring-projects/spring-boot/pull/38330)
-   Improve --help and documentation for "encodepassword -a/--algorithm" in the Spring Boot CLI [#&#8203;38203](https://togithub.com/spring-projects/spring-boot/issues/38203)
-   Document that TomcatConnectorCustomizers are not applied to additional connectors [#&#8203;38183](https://togithub.com/spring-projects/spring-boot/issues/38183)
-   MyErrorWebExceptionHandler example in documentation isn't working [#&#8203;38104](https://togithub.com/spring-projects/spring-boot/issues/38104)
-   Document that SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS is disabled by default [#&#8203;38083](https://togithub.com/spring-projects/spring-boot/issues/38083)
-   Update "Running Behind a Front-end Proxy Server" to include reactive and ForwardedHeaderTransformer [#&#8203;37282](https://togithub.com/spring-projects/spring-boot/issues/37282)
-   Improve documentation of `classpath.idx` file and its generation by the Maven and Gradle plugins [#&#8203;37125](https://togithub.com/spring-projects/spring-boot/issues/37125)
-   Document configuration for building images with Colima [#&#8203;34522](https://togithub.com/spring-projects/spring-boot/issues/34522)
-   Code sample in "Developing Your First Spring Boot Application" does not work [#&#8203;34513](https://togithub.com/spring-projects/spring-boot/issues/34513)
-   Document ConfigurationPropertyCaching [#&#8203;34172](https://togithub.com/spring-projects/spring-boot/issues/34172)
-   Document that application.\* banner variables require a packaged jar or the use of Boot's launcher [#&#8203;33489](https://togithub.com/spring-projects/spring-boot/issues/33489)
-   Add section on AspectJ support [#&#8203;32642](https://togithub.com/spring-projects/spring-boot/issues/32642)
-   Document server.servlet.encoding.\* properties and server.servlet.encoding.mapping in particular [#&#8203;32472](https://togithub.com/spring-projects/spring-boot/issues/32472)
-   Add a section on customizing embedded reactive servers [#&#8203;31917](https://togithub.com/spring-projects/spring-boot/issues/31917)
-   Clarify that MVC components provided through WebMvcRegistrations are subject to subsequent processing and configuration by MVC [#&#8203;31232](https://togithub.com/spring-projects/spring-boot/issues/31232)
-   Clarifying documentation on including a top-level `@TestConfiguration` class in a test [#&#8203;30513](https://togithub.com/spring-projects/spring-boot/issues/30513)
-   Clarify that `@AutoConfigureWebTestClient` binds WebTestClient to mock infrastructure [#&#8203;29890](https://togithub.com/spring-projects/spring-boot/issues/29890)
-   Improve systemd configuration documentation [#&#8203;28453](https://togithub.com/spring-projects/spring-boot/issues/28453)
-   Document how to customize the basePackages that auto-configurations consider (for example Spring Data Repositories) [#&#8203;27549](https://togithub.com/spring-projects/spring-boot/issues/27549)
-   Document additional user configuration that's required after setting `spring.hateoas.use-hal-as-default-json-media-type` to `false` [#&#8203;26814](https://togithub.com/spring-projects/spring-boot/issues/26814)
-   Add how-to documentation for test-only database migrations with Flyway/Liquibase [#&#8203;26796](https://togithub.com/spring-projects/spring-boot/issues/26796)

#### :hammer: Dependency Upgrades

-   Upgrade to ActiveMQ 5.16.7 [#&#8203;38427](https://togithub.com/spring-projects/spring-boot/issues/38427)
-   Upgrade to DB2 JDBC 11.5.9.0 [#&#8203;38428](https://togithub.com/spring-projects/spring-boot/issues/38428)
-   Upgrade to Dropwizard Metrics 4.2.22 [#&#8203;38429](https://togithub.com/spring-projects/spring-boot/issues/38429)
-   Upgrade to Elasticsearch 7.17.15 [#&#8203;38430](https://togithub.com/spring-projects/spring-boot/issues/38430)
-   Upgrade to Glassfish JAXB 2.3.9 [#&#8203;38431](https://togithub.com/spring-projects/spring-boot/issues/38431)
-   Upgrade to Micrometer 1.9.17 [#&#8203;38279](https://togithub.com/spring-projects/spring-boot/issues/38279)
-   Upgrade to Netty 4.1.101.Final [#&#8203;38432](https://togithub.com/spring-projects/spring-boot/issues/38432)
-   Upgrade to Pooled JMS 1.2.6 [#&#8203;38433](https://togithub.com/spring-projects/spring-boot/issues/38433)
-   Upgrade to Reactor Bom 2020.0.38 [#&#8203;38280](https://togithub.com/spring-projects/spring-boot/issues/38280)
-   Upgrade to Spring Batch 4.3.10 [#&#8203;38281](https://togithub.com/spring-projects/spring-boot/issues/38281)
-   Upgrade to Spring Data Bom 2021.2.18 [#&#8203;38282](https://togithub.com/spring-projects/spring-boot/issues/38282)
-   Upgrade to Spring Framework 5.3.31 [#&#8203;38283](https://togithub.com/spring-projects/spring-boot/issues/38283)
-   Upgrade to Spring HATEOAS 1.5.6 [#&#8203;38373](https://togithub.com/spring-projects/spring-boot/issues/38373)
-   Upgrade to Spring Integration 5.5.20 [#&#8203;38491](https://togithub.com/spring-projects/spring-boot/issues/38491)
-   Upgrade to Spring RESTDocs 2.0.8.RELEASE [#&#8203;38434](https://togithub.com/spring-projects/spring-boot/issues/38434)
-   Upgrade to Spring WS 3.1.8 [#&#8203;38284](https://togithub.com/spring-projects/spring-boot/issues/38284)
-   Upgrade to Tomcat 9.0.83 [#&#8203;38435](https://togithub.com/spring-projects/spring-boot/issues/38435)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;GVictorG7](https://togithub.com/GVictorG7), [@&#8203;PENEKhun](https://togithub.com/PENEKhun), [@&#8203;dreis2211](https://togithub.com/dreis2211), and [@&#8203;izeye](https://togithub.com/izeye)

### [`v2.7.17`](https://togithub.com/spring-projects/spring-boot/releases/tag/v2.7.17)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.7.16...v2.7.17)

##### :warning: Noteworthy Changes

-   The behavior of `spring.jms.listener.concurrency` has been corrected to match the documentation ([#&#8203;37180](https://togithub.com/spring-projects/spring-boot/pull/37180)). If you were setting `spring.jms.listener.concurrency` without also setting `spring.jms.listener.max-concurrency`, please review your configuration when upgrading.

##### :lady_beetle: Bug Fixes

-   `@Order` does not work on (CommandLine|Application)Runner `@Bean` methods [#&#8203;37905](https://togithub.com/spring-projects/spring-boot/pull/37905)
-   Gradle plugin uses to-be-deprecated API for getting and setting file permissions [#&#8203;37878](https://togithub.com/spring-projects/spring-boot/issues/37878)
-   Task executor metrics are not registered when using lazy initialization [#&#8203;37832](https://togithub.com/spring-projects/spring-boot/issues/37832)
-   Constructor binding with a custom collection type does not work [#&#8203;37734](https://togithub.com/spring-projects/spring-boot/issues/37734)
-   Dependency management for kafka-server-common with a test classifier is missing [#&#8203;37499](https://togithub.com/spring-projects/spring-boot/issues/37499)
-   fileMode and dirMode are not applied to all entries in an archive produced by BootJar [#&#8203;37496](https://togithub.com/spring-projects/spring-boot/issues/37496)
-   Gradle plugin's build info support produces a deprecation warning when using Gradle 8.4-rc-1 [#&#8203;37493](https://togithub.com/spring-projects/spring-boot/issues/37493)
-   RepackageMojo doesn't support 1 digit numerical values for project.build.outputTimestamp [#&#8203;37438](https://togithub.com/spring-projects/spring-boot/pull/37438)
-   Restarter creates memory leak in tests [#&#8203;37373](https://togithub.com/spring-projects/spring-boot/issues/37373)
-   Contrary to the documentation, setting spring.jms.listener.concurrency alone configures the maximum concurrency [#&#8203;37180](https://togithub.com/spring-projects/spring-boot/pull/37180)
-   Application fails to start when an optional config import cannot be resolved [#&#8203;35683](https://togithub.com/spring-projects/spring-boot/issues/35683)
-   `@ComponentScan` on a test class is processed when creating a test context but is not included in the context's cache key [#&#8203;31577](https://togithub.com/spring-projects/spring-boot/issues/31577)
-   AspectJ transaction management with compile-time weaving does not work with spring.main.lazy-initialization=true [#&#8203;37506](https://togithub.com/spring-projects/spring-boot/issues/37506)

##### :notebook_with_decorative_cover: Documentation

-   Remove link to LiveReload website due to timeout [#&#8203;37643](https://togithub.com/spring-projects/spring-boot/pull/37643)
-   Refer to ActiveMQ as ActiveMQ "Classic" [#&#8203;37606](https://togithub.com/spring-projects/spring-boot/pull/37606)
-   Use more idiomatic Kotlin in example for "Map Health Indicators to Micrometer Metrics" [#&#8203;37491](https://togithub.com/spring-projects/spring-boot/pull/37491)
-   Document support for Java 21 [#&#8203;37371](https://togithub.com/spring-projects/spring-boot/issues/37371)

##### :hammer: Dependency Upgrades

-   Upgrade to Dropwizard Metrics 4.2.21 [#&#8203;37893](https://togithub.com/spring-projects/spring-boot/issues/37893)
-   Upgrade to Elasticsearch 7.17.14 [#&#8203;37840](https://togithub.com/spring-projects/spring-boot/issues/37840)
-   Upgrade to Infinispan 13.0.20.Final [#&#8203;37841](https://togithub.com/spring-projects/spring-boot/issues/37841)
-   Upgrade to Jetty 9.4.53.v20231009 [#&#8203;37842](https://togithub.com/spring-projects/spring-boot/issues/37842)
-   Upgrade to Jetty Reactive HTTPClient 1.1.15 [#&#8203;37927](https://togithub.com/spring-projects/spring-boot/issues/37927)
-   Upgrade to Micrometer 1.9.16 [#&#8203;37674](https://togithub.com/spring-projects/spring-boot/issues/37674)
-   Upgrade to Netty 4.1.100.Final [#&#8203;37843](https://togithub.com/spring-projects/spring-boot/issues/37843)
-   Upgrade to Pooled JMS 1.2.5 [#&#8203;37894](https://togithub.com/spring-projects/spring-boot/issues/37894)
-   Upgrade to Reactor Bom 2020.0.37 [#&#8203;37675](https://togithub.com/spring-projects/spring-boot/issues/37675)
-   Upgrade to Spring AMQP 2.4.17 [#&#8203;37676](https://togithub.com/spring-projects/spring-boot/issues/37676)
-   Upgrade to Spring Data Bom 2021.2.17 [#&#8203;37677](https://togithub.com/spring-projects/spring-boot/issues/37677)
-   Upgrade to Spring Session Bom 2021.2.3 [#&#8203;37928](https://togithub.com/spring-projects/spring-boot/issues/37928)
-   Upgrade to Tomcat 9.0.82 [#&#8203;37895](https://togithub.com/spring-projects/spring-boot/issues/37895)
-   Upgrade to UnboundID LDAPSDK 6.0.10 [#&#8203;37753](https://togithub.com/spring-projects/spring-boot/issues/37753)
-   Upgrade to Undertow 2.2.28.Final [#&#8203;37929](https://togithub.com/spring-projects/spring-boot/issues/37929)

##### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;bottlerocketjonny](https://togithub.com/bottlerocketjonny), [@&#8203;dependabot](https://togithub.com/dependabot)\[bot], [@&#8203;erichaagdev](https://togithub.com/erichaagdev), [@&#8203;esperar](https://togithub.com/esperar), [@&#8203;izeye](https://togithub.com/izeye), [@&#8203;jbertram](https://togithub.com/jbertram), [@&#8203;nielsbasjes](https://togithub.com/nielsbasjes), [@&#8203;onobc](https://togithub.com/onobc), [@&#8203;ttddyy](https://togithub.com/ttddyy), and [@&#8203;vpavic](https://togithub.com/vpavic)

### [`v2.7.16`](https://togithub.com/spring-projects/spring-boot/releases/tag/v2.7.16)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.7.15...v2.7.16)

##### :star: New Features

-   Add TWENTY_ONE to JavaVersion enum [#&#8203;37362](https://togithub.com/spring-projects/spring-boot/issues/37362)

##### :lady_beetle: Bug Fixes

-   Invalid Accept header produces HTTP 500 in WelcomePageHandlerMapping [#&#8203;37455](https://togithub.com/spring-projects/spring-boot/issues/37455)
-   PrivateKeyParser doesn't support ed448, XDH and RSA-PSS keys [#&#8203;37237](https://togithub.com/spring-projects/spring-boot/issues/37237)
-   Parsing OCI image names that are invalid due to the use of upper case letters is very slow [#&#8203;35657](https://togithub.com/spring-projects/spring-boot/issues/35657)
-   Using https with elliptic curves other than secp384r1 fails [#&#8203;34232](https://togithub.com/spring-projects/spring-boot/issues/34232)
-   Saml2RelyingPartyAutoConfiguration ignores `sign-request` when `metadata-url` is used [#&#8203;33747](https://togithub.com/spring-projects/spring-boot/issues/33747)
-   Leaking file descriptor / socket within DomainSocket tooling [#&#8203;32423](https://togithub.com/spring-projects/spring-boot/issues/32423)

##### :notebook_with_decorative_cover: Documentation

-   Correct the description of spring.artemis.broker-url [#&#8203;37260](https://togithub.com/spring-projects/spring-boot/pull/37260)
-   Add default value metadata for management.metrics.export.signalfx.published-histogram-type [#&#8203;37210](https://togithub.com/spring-projects/spring-boot/pull/37210)
-   Document that PKCS8 PEM files should be used whenever possible [#&#8203;37170](https://togithub.com/spring-projects/spring-boot/issues/37170)
-   Polish javadoc [#&#8203;37112](https://togithub.com/spring-projects/spring-boot/pull/37112)

##### :hammer: Dependency Upgrades

-   Upgrade to Elasticsearch 7.17.13 [#&#8203;37286](https://togithub.com/spring-projects/spring-boot/issues/37286)
-   Upgrade to Jetty 9.4.52.v20230823 [#&#8203;37287](https://togithub.com/spring-projects/spring-boot/issues/37287)
-   Upgrade to Lombok 1.18.30 [#&#8203;37486](https://togithub.com/spring-projects/spring-boot/issues/37486)
-   Upgrade to Micrometer 1.9.15 [#&#8203;37245](https://togithub.com/spring-projects/spring-boot/issues/37245)
-   Upgrade to Reactor Bom 2020.0.36 [#&#8203;37246](https://togithub.com/spring-projects/spring-boot/issues/37246)
-   Upgrade to Spring AMQP 2.4.16 [#&#8203;37247](https://togithub.com/spring-projects/spring-boot/issues/37247)
-   Upgrade to Spring Data Bom 2021.2.16 [#&#8203;37248](https://togithub.com/spring-projects/spring-boot/issues/37248)
-   Upgrade to Spring Framework 5.3.30 [#&#8203;37249](https://togithub.com/spring-projects/spring-boot/issues/37249)
-   Upgrade to Spring GraphQL 1.0.6 [#&#8203;37250](https://togithub.com/spring-projects/spring-boot/issues/37250)
-   Upgrade to Spring Integration 5.5.19 [#&#8203;37251](https://togithub.com/spring-projects/spring-boot/issues/37251)
-   Upgrade to Spring Security 5.7.11 [#&#8203;37414](https://togithub.com/spring-projects/spring-boot/issues/37414)
-   Upgrade to Spring WS 3.1.7 [#&#8203;37415](https://togithub.com/spring-projects/spring-boot/issues/37415)
-   Upgrade to Tomcat 9.0.80 [#&#8203;37288](https://togithub.com/spring-projects/spring-boot/issues/37288)

##### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;dependabot](https://togithub.com/dependabot)\[bot], [@&#8203;hakan-krgn](https://togithub.com/hakan-krgn), [@&#8203;izeye](https://togithub.com/izeye), [@&#8203;mdeinum](https://togithub.com/mdeinum), and [@&#8203;quaff](https://togithub.com/quaff)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/GoogleCloudPlatform/cloud-code-samples).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy41OS44IiwidXBkYXRlZEluVmVyIjoiMzcuNTkuOCIsInRhcmdldEJyYW5jaCI6InYxIn0=-->